name: PlatformIO CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        test_config: [with_config_file, without_config_file]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # Only copy config.h if test_config == "with_config_file"
      - name: Create config.h
        if: ${{ matrix.test_config == 'with_config_file' }}
        run: cp firmware/config/config.h.template firmware/config/config.h

      # IMPORTANT: Build from the repo root (since platformio.ini is in root)
      - name: Build PlatformIO Project
        run: pio run

      # Upload artifact on Ubuntu only, naming it firmware-with_config_file or firmware-without_config_file
      - name: Upload artifact on ubuntu-latest
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.test_config }}
          path: .pio/build/esp32doit-devkit-v1/firmware.bin

      - name: Output artifact URL
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
