name: PlatformIO CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        test_config: [with_file, without_file]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # Conditionally copy the orb_config.h only in "with_file" builds
      - name: Create orb_config.h
        if: ${{ matrix.test_config == 'with_file' }}
        working-directory: ./firmware
        run: cp config/orb_config.h.template config/orb_config.h

      - name: Build PlatformIO Project
        working-directory: ./firmware
        run: pio run

      # Upload artifacts for each test config on Ubuntu only (optional)
      - name: Upload artifact on ubuntu-latest
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          # Name includes the test_config so you know which artifact is which
          name: firmware-${{ matrix.test_config }}
          path: .pio/build/esp32doit-devkit-v1/firmware.bin

      - name: Output artifact URL
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
